name: CI Pipeline

# Trigger the workflow on push to the 'main' branch or pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs (tasks) to run in the workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python (if you are using Python)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify the Python version you want to use

      # Step 3: Install dependencies (using pip for Python)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (using pytest as an example)
      # - name: Run tests
      #   run: |
      #     pytest  # Replace this with your test command
