name: Build and Push Docker Image


on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch or pull requests

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx (for multi-platform builds)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username from GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password or token from GitHub Secrets
          email: ${{ secrets.DOCKER_EMAIL }}  

      - name: Build Docker image
        run: |
          docker build -t arshraj/topic-modeling-streamlit:latest .  # Replace with your Docker Hub repo and tag

      - name: Push Docker image to Docker Hub
        run: |
          docker push arshraj/topic-modeling-streamlit:latest  # Replace with your Docker Hub repo